/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 shoe.glb
*/
'use client'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';

export function Model(props) {
  const { nodes, materials } = useGLTF('/shoe.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.01, 0.56, -1.22]} scale={0.43}>
        <mesh geometry={nodes.Cube002.geometry} material={materials.Upper} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['BottumBack.001']} />
      </group>
      <group position={[-0.05, 0.5, -0.55]} rotation={[0.63, 0, 0]}>
        <mesh geometry={nodes.Plane.geometry} material={materials['Upper.001']} />
        <mesh geometry={nodes.Plane_1.geometry} material={materials['BottumBack.001']} />
      </group>
      <group position={[-0.02, 0.43, -0.52]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials.Main} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.Upper} />
      </group>
      <mesh geometry={nodes.AIr_Max_Logo_2.geometry} material={materials['BottumBack.002']} position={[-0.01, 0.54, -1.57]} rotation={[Math.PI / 2, 0.89, Math.PI]} scale={0.02} />
      <mesh geometry={nodes.Back.geometry} material={materials.BottumBack} position={[0, 0.1, -1.24]} />
      <mesh geometry={nodes.AIr_Max_Logo_1.geometry} material={materials['BottumBack.002']} position={[-0.02, 0.9, -0.85]} scale={0.01} />
      <mesh geometry={nodes.Stitches.geometry} material={materials['Material.001']} position={[-0.03, 0.52, -0.64]} scale={0} />
      <mesh geometry={nodes.NikeLogo1.geometry} material={materials['Middle Sole']} position={[-0.03, 0.4, -0.85]} scale={[-0.22, -0.22, -0.09]} />
      <mesh geometry={nodes.NikeLogo2.geometry} material={materials['Middle Sole']} position={[0.02, 0.12, 0.37]} scale={[0.49, 0.3, 0.4]} />
      <mesh geometry={nodes.Sides.geometry} material={materials.SIDEDESIGN} position={[0.08, 0.15, -0.61]} scale={0.36} />
      <mesh geometry={nodes.Rings.geometry} material={materials['BottumBack.001']} position={[-0.04, 0.54, -0.48]} rotation={[0.46, 0.26, -0.46]} scale={0.83} />
      <mesh geometry={nodes.Front.geometry} material={materials['SIDEDESIGN.001']} position={[0.02, 0.12, 0.37]} scale={[0.49, 0.3, 0.4]} />
      <mesh geometry={nodes.Hook.geometry} material={materials['BottumBack.001']} position={[0.02, 0.83, -1.45]} rotation={[Math.PI / 2, 0, 0]} scale={[0.67, 0.7, 0.92]} />
      <mesh geometry={nodes.Laces.geometry} material={materials['Upper.002']} position={[-0.04, 0.57, -0.45]} scale={-0.28} />
      <mesh geometry={nodes.Middle_back.geometry} material={materials['Back(Brick)']} position={[0, 0.32, -1.18]} />
      <mesh geometry={nodes.Very_bottum.geometry} material={materials['Bottum Sole']} position={[-0.01, -0.11, -0.88]} />
      <mesh geometry={nodes.Parent001.geometry} material={materials['Middle Sole.001']} position={[-0.03, 0, -0.03]} rotation={[0, -0.03, 0]} />
    </group>
  )
}

useGLTF.preload('/shoe.glb')
